{{- $svc_name := printf "%s-%s" .Release.Namespace .Chart.Name -}}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ $svc_name }}-destination-rule
  namespace: {{ .Values.global.istio_ingress_namespace }}
  labels:
    {{- if .Values.global.istio_revision_name }}
    istio.io/rev: "{{ .Values.global.istio_revision_name }}"
    {{- end }}
spec:
  host: {{ $svc_name }}.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 9000
