{{- $previous := lookup "v1" "Secret" .Release.Namespace (include "postgresql.secretName" .) }}
{{- if $previous }}  # upgrade
# `index` function is necessary because the property name contains a dash.
# Otherwise $previous.data.postgresql_password would have worked too.
{{- $postgresqlPassword :=  index $previous.data "postgresql-password" }}
{{- $postgresqlUsername :=  index $previous.data "postgresql-username" }}
{{- $postgresqlDb := index $previous.data "postgresql-db" }}
{{- $spiceDbPassword := default (randAlphaNum 12 | b64enc | quote) (index $previous.data "spicedb-postgresql-password") }}
{{- $spiceDbUsername := default (randAlpha 6 | lower | b64enc | quote) (index $previous.data "spicedb-postgresql-username") }}
{{- $flyteDb := index $previous.data "flyte-postgresql-db" }}
{{- $flyteDbPassword := index $previous.data "flyte-postgresql-password" }}
{{- $flyteDbUsername := index $previous.data "flyte-postgresql-username" }}
{{- $accountserviceDb := default (.Values.postgresql.accountservice_postgresql_db | b64enc | quote) (index $previous.data "accountservice-postgresql-db") }}
{{- $accountserviceDbPassword := default (randAlphaNum 12 | b64enc | quote) (index $previous.data "accountservice-postgresql-password") }}
{{- $accountserviceDbUsername := default (randAlpha 6 | lower | b64enc | quote) (index $previous.data "accountservice-postgresql-username") }}
{{- $creditsystemDb := default (.Values.postgresql.accountservice_postgresql_db | b64enc | quote) (index $previous.data "creditsystem-postgresql-db") }}
{{- $creditsystemDbPassword := default (randAlphaNum 12 | b64enc | quote) (index $previous.data "creditsystem-postgresql-password") }}
{{- $creditsystemDbUsername := default (randAlpha 6 | lower | b64enc | quote) (index $previous.data "creditsystem-postgresql-username") }}

# Secret for platform namespace
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  postgresql-password: {{ $postgresqlPassword }}
  postgresql-username: {{ $postgresqlUsername }}
  postgresql-db: {{ $postgresqlDb }}
  spicedb-postgresql-password: {{ $spiceDbPassword }}
  spicedb-postgresql-username: {{ $spiceDbUsername }}
  accountservice-postgresql-db: {{ $accountserviceDb }}
  accountservice-postgresql-password: {{ $accountserviceDbPassword }}
  accountservice-postgresql-username: {{ $accountserviceDbUsername }}
  creditsystem-postgresql-db: {{ $creditsystemDb }}
  creditsystem-postgresql-password: {{ $creditsystemDbPassword }}
  creditsystem-postgresql-username: {{ $creditsystemDbUsername }}
  flyte-postgresql-db: {{ $flyteDb }}
  flyte-postgresql-password: {{ $flyteDbPassword }}
  flyte-postgresql-username: {{ $flyteDbUsername }}
{{- if .Values.postgresql.flyte_db_enabled }}
# Secret for flyte namespace
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.secretName" . }}
  namespace: "flyte"
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  postgresql-password: {{ $postgresqlPassword }}
  postgresql-username: {{ $postgresqlUsername }}
  postgresql-db: {{ $postgresqlDb }}
  flyte-postgresql-db: {{ $flyteDb }}
  flyte-postgresql-password: {{ $flyteDbPassword }}
  flyte-postgresql-username: {{ $flyteDbUsername }}
{{- end }}
# installation case
{{ else }}
{{- $postgresqlPassword :=  randAlphaNum 12 | b64enc | quote }}
{{- $postgresqlUsername := randAlpha 6 | lower | b64enc | quote }}
{{- $spiceDbPassword := randAlphaNum 12  | b64enc | quote }}
{{- $spiceDbUsername := randAlpha 6 | lower | b64enc | quote }}
{{- $flyteDbPassword := randAlphaNum 12 }}
{{- $flyteDbUsername := randAlpha 6 | lower }}
{{- $accountserviceDbPassword := randAlphaNum 12 | b64enc | quote }}
{{- $accountserviceDbUsername := randAlpha 6 | lower | b64enc | quote  }}
{{- $creditsystemDbPassword := randAlphaNum 12 | b64enc | quote }}
{{- $creditsystemDbUsername := randAlpha 6 | lower | b64enc | quote  }}
# Secret for platform namespace
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  postgresql-password: {{ $postgresqlPassword }}
  postgresql-username: {{ $postgresqlUsername }}
  spicedb-postgresql-password: {{ $spiceDbPassword }}
  spicedb-postgresql-username: {{ $spiceDbUsername }}
  accountservice-postgresql-password: {{ $accountserviceDbPassword }}
  accountservice-postgresql-username: {{ $accountserviceDbUsername }}
  {{- if .Values.global.credit_system_enabled }}
  creditsystem-postgresql-password: {{ $creditsystemDbPassword }}
  creditsystem-postgresql-username: {{ $creditsystemDbUsername }}
  {{- end }}
stringData:
  flyte-postgresql-password: "{{ $flyteDbPassword }}"
  flyte-postgresql-username: "{{ $flyteDbUsername }}"

{{- if .Values.postgresql.flyte_db_enabled }}
# Secret for flyte namespace
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.secretName" . }}
  namespace: "flyte"
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  postgresql-password: {{ $postgresqlPassword }}
  postgresql-username: {{ $postgresqlUsername }}
stringData:
  flyte-postgresql-password: "{{ $flyteDbPassword }}"
  flyte-postgresql-username: "{{ $flyteDbUsername }}"
{{- end }}
{{- end }}
